import { AssetType, Category } from '../../features/categories/models/category.model';

export type MockAssetCategoryId = 'technology' | 'furniture' | 'laboratory' | 'sports';
export type MockAssetLocationId =
  | 'classroom-101'
  | 'computer-lab'
  | 'auditorium'
  | 'teachers-room'
  | 'science-lab'
  | 'sports-warehouse';
export type MockAssetCondition =
  | 'Bueno'
  | 'Regular'
  | 'Malo'
  | 'Mantenimiento'
  | 'Dado de baja';

export interface MockLoanDestination {
  id: string;
  name: string;
}

export interface MockAssetLocation extends MockLoanDestination {
  id: MockAssetLocationId;
}

export interface MockInventoryAsset {
  id: string;
  name: string;
  code: string;
  condition: MockAssetCondition;
  categoryId: MockAssetCategoryId;
  typeId: string;
  groupKey: string;
  groupName: string;
  groupIcon: string;
  serial: string;
  locationId: MockAssetLocationId;
  location: string;
}

interface MockCategoryDefinition {
  id: string;
  key: MockAssetCategoryId;
  name: string;
  icon: string;
  types: AssetType[];
}

export const MOCK_LOAN_DESTINATIONS: MockAssetLocation[] = [
  { id: 'classroom-101', name: 'Aula 101 - Pabellón A' },
  { id: 'computer-lab', name: 'Laboratorio de Cómputo' },
  { id: 'auditorium', name: 'Auditorio Principal' },
  { id: 'teachers-room', name: 'Sala de Profesores' },
  { id: 'science-lab', name: 'Laboratorio de Ciencias' },
  { id: 'sports-warehouse', name: 'Almacén Deportivo' },
];

export const MOCK_ASSET_LOCATIONS: MockAssetLocation[] = [...MOCK_LOAN_DESTINATIONS];

const MOCK_CATEGORY_DEFINITIONS: MockCategoryDefinition[] = [
  {
    id: '1',
    key: 'technology',
    name: 'Tecnología',
    icon: 'devices',
    types: [
      {
        id: 'tech-laptop',
        name: 'Laptop',
        icon: 'laptop_mac',
        attributes: [
          { id: 'attr-tech-laptop-brand', name: 'Marca', description: 'Fabricante del equipo', isRequired: true },
          { id: 'attr-tech-laptop-model', name: 'Modelo', description: 'Modelo comercial del equipo', isRequired: true },
          { id: 'attr-tech-laptop-cpu', name: 'Procesador', description: 'CPU instalada', isRequired: false },
          { id: 'attr-tech-laptop-ram', name: 'RAM (GB)', description: 'Capacidad de memoria RAM', isRequired: false },
        ],
      },
      {
        id: 'tech-desktop',
        name: 'Desktop',
        icon: 'desktop_windows',
        attributes: [
          { id: 'attr-tech-desktop-brand', name: 'Marca', description: 'Fabricante del equipo', isRequired: true },
          { id: 'attr-tech-desktop-model', name: 'Modelo', description: 'Modelo del CPU o all-in-one', isRequired: true },
          { id: 'attr-tech-desktop-storage', name: 'Almacenamiento', description: 'Capacidad del disco principal', isRequired: false },
        ],
      },
      {
        id: 'tech-projector',
        name: 'Proyector',
        icon: 'present_to_all',
        attributes: [
          { id: 'attr-tech-projector-brand', name: 'Marca', description: 'Fabricante del proyector', isRequired: true },
          { id: 'attr-tech-projector-resolution', name: 'Resolución', description: 'Resolución nativa', isRequired: true },
          { id: 'attr-tech-projector-lumens', name: 'Lumens', description: 'Brillo en ANSI lumens', isRequired: false },
        ],
      },
      {
        id: 'tech-router',
        name: 'Router',
        icon: 'router',
        attributes: [
          { id: 'attr-tech-router-brand', name: 'Marca', description: 'Fabricante del router', isRequired: true },
          { id: 'attr-tech-router-standard', name: 'Estándar Wi-Fi', description: 'Estándar inalámbrico soportado', isRequired: true },
          { id: 'attr-tech-router-ports', name: 'Puertos LAN', description: 'Cantidad de puertos de red', isRequired: false },
        ],
      },
      {
        id: 'tech-webcam',
        name: 'Webcam',
        icon: 'videocam',
        attributes: [
          { id: 'attr-tech-webcam-brand', name: 'Marca', description: 'Fabricante de la webcam', isRequired: true },
          { id: 'attr-tech-webcam-resolution', name: 'Resolución', description: 'Resolución de captura', isRequired: true },
          { id: 'attr-tech-webcam-mic', name: 'Micrófono integrado', description: 'Disponibilidad de micrófono', isRequired: false },
        ],
      },
      {
        id: 'tech-printer',
        name: 'Impresora',
        icon: 'print',
        attributes: [
          { id: 'attr-tech-printer-brand', name: 'Marca', description: 'Fabricante de la impresora', isRequired: true },
          { id: 'attr-tech-printer-print-type', name: 'Tecnología', description: 'Láser, tinta u otra tecnología', isRequired: true },
          { id: 'attr-tech-printer-connectivity', name: 'Conectividad', description: 'USB, red o Wi-Fi', isRequired: false },
        ],
      },
      {
        id: 'tech-tablet',
        name: 'Tablet',
        icon: 'tablet_mac',
        attributes: [
          { id: 'attr-tech-tablet-brand', name: 'Marca', description: 'Fabricante de la tablet', isRequired: true },
          { id: 'attr-tech-tablet-model', name: 'Modelo', description: 'Modelo comercial', isRequired: true },
          { id: 'attr-tech-tablet-storage', name: 'Almacenamiento', description: 'Capacidad interna', isRequired: false },
        ],
      },
      {
        id: 'tech-monitor',
        name: 'Monitor',
        icon: 'monitor',
        attributes: [
          { id: 'attr-tech-monitor-brand', name: 'Marca', description: 'Fabricante del monitor', isRequired: true },
          { id: 'attr-tech-monitor-size', name: 'Tamaño', description: 'Medida en pulgadas', isRequired: true },
          { id: 'attr-tech-monitor-resolution', name: 'Resolución', description: 'Resolución máxima', isRequired: false },
        ],
      },
      {
        id: 'tech-microphone',
        name: 'Micrófono',
        icon: 'mic_external_on',
        attributes: [
          { id: 'attr-tech-microphone-brand', name: 'Marca', description: 'Fabricante del micrófono', isRequired: true },
          { id: 'attr-tech-microphone-type', name: 'Tipo', description: 'De mano, lavalier o headset', isRequired: true },
          { id: 'attr-tech-microphone-frequency', name: 'Frecuencia', description: 'Rango de operación', isRequired: false },
        ],
      },
      {
        id: 'tech-hdmi-cable',
        name: 'Cable HDMI',
        icon: 'settings_input_hdmi',
        attributes: [
          { id: 'attr-tech-hdmi-cable-length', name: 'Longitud', description: 'Longitud del cable en metros', isRequired: true },
          { id: 'attr-tech-hdmi-cable-version', name: 'Versión', description: 'Versión del estándar HDMI', isRequired: false },
          { id: 'attr-tech-hdmi-cable-state', name: 'Estado físico', description: 'Estado físico del accesorio', isRequired: false },
        ],
      },
      {
        id: 'tech-laser-pointer',
        name: 'Puntero Láser',
        icon: 'ads_click',
        attributes: [
          { id: 'attr-tech-laser-pointer-brand', name: 'Marca', description: 'Fabricante del puntero', isRequired: true },
          { id: 'attr-tech-laser-pointer-range', name: 'Alcance', description: 'Distancia máxima de proyección', isRequired: false },
          { id: 'attr-tech-laser-pointer-power', name: 'Alimentación', description: 'Tipo de batería o carga', isRequired: false },
        ],
      },
    ],
  },
  {
    id: '2',
    key: 'furniture',
    name: 'Mobiliario',
    icon: 'chair',
    types: [
      {
        id: 'furniture-desk',
        name: 'Escritorio',
        icon: 'table_restaurant',
        attributes: [
          { id: 'attr-furniture-desk-material', name: 'Material', description: 'Material principal del escritorio', isRequired: true },
          { id: 'attr-furniture-desk-dimensions', name: 'Dimensiones', description: 'Medidas aproximadas del escritorio', isRequired: false },
          { id: 'attr-furniture-desk-finish', name: 'Acabado', description: 'Color o acabado principal', isRequired: false },
        ],
      },
      {
        id: 'furniture-chair',
        name: 'Silla',
        icon: 'chair',
        attributes: [
          { id: 'attr-furniture-chair-material', name: 'Material', description: 'Material estructural o de tapizado', isRequired: true },
          { id: 'attr-furniture-chair-type', name: 'Tipo', description: 'Fija, ergonómica o giratoria', isRequired: true },
          { id: 'attr-furniture-chair-adjustment', name: 'Ajustable', description: 'Capacidad de ajuste de altura o respaldo', isRequired: false },
        ],
      },
      {
        id: 'furniture-file-cabinet',
        name: 'Archivador',
        icon: 'inventory_2',
        attributes: [
          { id: 'attr-furniture-file-cabinet-drawers', name: 'Número de gavetas', description: 'Cantidad de compartimentos', isRequired: true },
          { id: 'attr-furniture-file-cabinet-lock', name: 'Cerradura', description: 'Disponibilidad de llave o sistema de bloqueo', isRequired: false },
          { id: 'attr-furniture-file-cabinet-material', name: 'Material', description: 'Material principal del archivador', isRequired: false },
        ],
      },
      {
        id: 'furniture-shelf',
        name: 'Estante',
        icon: 'inventory_2',
        attributes: [
          { id: 'attr-furniture-shelf-levels', name: 'Niveles', description: 'Cantidad de niveles o repisas', isRequired: true },
          { id: 'attr-furniture-shelf-load', name: 'Capacidad de carga', description: 'Peso máximo por nivel', isRequired: false },
          { id: 'attr-furniture-shelf-material', name: 'Material', description: 'Material estructural', isRequired: false },
        ],
      },
    ],
  },
  {
    id: '3',
    key: 'laboratory',
    name: 'Laboratorio',
    icon: 'science',
    types: [
      {
        id: 'lab-microscope',
        name: 'Microscopio',
        icon: 'biotech',
        attributes: [
          { id: 'attr-lab-microscope-brand', name: 'Marca', description: 'Fabricante del microscopio', isRequired: true },
          { id: 'attr-lab-microscope-magnification', name: 'Aumento', description: 'Capacidad máxima de aumento', isRequired: true },
          { id: 'attr-lab-microscope-lighting', name: 'Iluminación', description: 'Tipo de iluminación incorporada', isRequired: false },
        ],
      },
      {
        id: 'lab-scale',
        name: 'Balanza Digital',
        icon: 'scale',
        attributes: [
          { id: 'attr-lab-scale-brand', name: 'Marca', description: 'Fabricante de la balanza', isRequired: true },
          { id: 'attr-lab-scale-capacity', name: 'Capacidad', description: 'Peso máximo soportado', isRequired: true },
          { id: 'attr-lab-scale-precision', name: 'Precisión', description: 'Precisión o sensibilidad del equipo', isRequired: false },
        ],
      },
      {
        id: 'lab-chemistry-kit',
        name: 'Kit de Química',
        icon: 'science',
        attributes: [
          { id: 'attr-lab-chemistry-kit-components', name: 'Componentes', description: 'Lista o cantidad de elementos incluidos', isRequired: true },
          { id: 'attr-lab-chemistry-kit-grade', name: 'Nivel', description: 'Nivel educativo o de complejidad', isRequired: false },
          { id: 'attr-lab-chemistry-kit-safety', name: 'Implementos de seguridad', description: 'Equipos o materiales de seguridad incluidos', isRequired: false },
        ],
      },
      {
        id: 'lab-power-supply',
        name: 'Fuente de Poder',
        icon: 'power',
        attributes: [
          { id: 'attr-lab-power-supply-voltage', name: 'Rango de voltaje', description: 'Voltaje de salida configurable', isRequired: true },
          { id: 'attr-lab-power-supply-current', name: 'Corriente máxima', description: 'Corriente máxima soportada', isRequired: false },
          { id: 'attr-lab-power-supply-display', name: 'Pantalla digital', description: 'Presencia de display de lectura', isRequired: false },
        ],
      },
    ],
  },
  {
    id: '4',
    key: 'sports',
    name: 'Deportes',
    icon: 'sports_soccer',
    types: [
      {
        id: 'sports-ball',
        name: 'Balón',
        icon: 'sports_soccer',
        attributes: [
          { id: 'attr-sports-ball-discipline', name: 'Disciplina', description: 'Deporte o disciplina asociada', isRequired: true },
          { id: 'attr-sports-ball-size', name: 'Tamaño', description: 'Tamaño o numeración oficial', isRequired: true },
          { id: 'attr-sports-ball-material', name: 'Material', description: 'Material de fabricación', isRequired: false },
        ],
      },
      {
        id: 'sports-cone',
        name: 'Cono',
        icon: 'sports',
        attributes: [
          { id: 'attr-sports-cone-height', name: 'Altura', description: 'Altura del cono en centímetros', isRequired: true },
          { id: 'attr-sports-cone-color', name: 'Color', description: 'Color predominante del set', isRequired: false },
          { id: 'attr-sports-cone-quantity', name: 'Cantidad por set', description: 'Número de conos incluidos', isRequired: false },
        ],
      },
      {
        id: 'sports-mat',
        name: 'Colchoneta',
        icon: 'fitness_center',
        attributes: [
          { id: 'attr-sports-mat-dimensions', name: 'Dimensiones', description: 'Largo y ancho de la colchoneta', isRequired: true },
          { id: 'attr-sports-mat-thickness', name: 'Espesor', description: 'Espesor aproximado de la colchoneta', isRequired: false },
          { id: 'attr-sports-mat-material', name: 'Material', description: 'Material de recubrimiento', isRequired: false },
        ],
      },
      {
        id: 'sports-net',
        name: 'Red',
        icon: 'sports_volleyball',
        attributes: [
          { id: 'attr-sports-net-discipline', name: 'Disciplina', description: 'Uso principal de la red', isRequired: true },
          { id: 'attr-sports-net-length', name: 'Longitud', description: 'Medida total de la red', isRequired: false },
          { id: 'attr-sports-net-material', name: 'Material', description: 'Material de fabricación', isRequired: false },
        ],
      },
    ],
  },
];

export const MOCK_INVENTORY_ASSETS: MockInventoryAsset[] = [
  {
    id: 'asset-1',
    name: 'Laptop Lenovo ThinkPad T14',
    code: 'CMP-2023-045',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-laptop',
    groupKey: 'laptop-lenovo-thinkpad-t14',
    groupName: 'Laptops Lenovo ThinkPad T14',
    groupIcon: 'laptop_mac',
    serial: 'SN: LNV-T14-045',
    locationId: 'computer-lab',
    location: 'Laboratorio de Cómputo',
  },
  {
    id: 'asset-2',
    name: 'Laptop Lenovo ThinkPad T14',
    code: 'CMP-2023-046',
    condition: 'Regular',
    categoryId: 'technology',
    typeId: 'tech-laptop',
    groupKey: 'laptop-lenovo-thinkpad-t14',
    groupName: 'Laptops Lenovo ThinkPad T14',
    groupIcon: 'laptop_mac',
    serial: 'SN: LNV-T14-046',
    locationId: 'classroom-101',
    location: 'Aula 101 - Pabellón A',
  },
  {
    id: 'asset-3',
    name: 'Desktop Dell OptiPlex 7090',
    code: 'DES-2022-011',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-desktop',
    groupKey: 'desktop-dell-optiplex-7090',
    groupName: 'Desktop Dell OptiPlex 7090',
    groupIcon: 'desktop_windows',
    serial: 'SN: DLL-7090-011',
    locationId: 'computer-lab',
    location: 'Laboratorio de Cómputo',
  },
  {
    id: 'asset-27',
    name: 'Desktop Dell OptiPlex 7090',
    code: 'DES-2022-012',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-desktop',
    groupKey: 'desktop-dell-optiplex-7090',
    groupName: 'Desktop Dell OptiPlex 7090',
    groupIcon: 'desktop_windows',
    serial: 'SN: DLL-7090-012',
    locationId: 'computer-lab',
    location: 'Laboratorio de Cómputo',
  },
  {
    id: 'asset-4',
    name: 'Proyector Epson PowerLite E20',
    code: 'PRY-2022-012',
    condition: 'Regular',
    categoryId: 'technology',
    typeId: 'tech-projector',
    groupKey: 'proyector-epson-powerlite-e20',
    groupName: 'Proyectores Epson PowerLite E20',
    groupIcon: 'present_to_all',
    serial: 'SN: EPS-E20-012',
    locationId: 'auditorium',
    location: 'Auditorio Principal',
  },
  {
    id: 'asset-28',
    name: 'Proyector Epson PowerLite E20',
    code: 'PRY-2022-013',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-projector',
    groupKey: 'proyector-epson-powerlite-e20',
    groupName: 'Proyectores Epson PowerLite E20',
    groupIcon: 'present_to_all',
    serial: 'SN: EPS-E20-013',
    locationId: 'auditorium',
    location: 'Auditorio Principal',
  },
  {
    id: 'asset-5',
    name: 'Router TP-Link Archer C80',
    code: 'NET-2024-005',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-router',
    groupKey: 'router-tplink-archer-c80',
    groupName: 'Routers TP-Link Archer C80',
    groupIcon: 'router',
    serial: 'SN: TPL-C80-005',
    locationId: 'classroom-101',
    location: 'Aula 101 - Pabellón A',
  },
  {
    id: 'asset-29',
    name: 'Router TP-Link Archer C80',
    code: 'NET-2024-006',
    condition: 'Regular',
    categoryId: 'technology',
    typeId: 'tech-router',
    groupKey: 'router-tplink-archer-c80',
    groupName: 'Routers TP-Link Archer C80',
    groupIcon: 'router',
    serial: 'SN: TPL-C80-006',
    locationId: 'classroom-101',
    location: 'Aula 101 - Pabellón A',
  },
  {
    id: 'asset-6',
    name: 'Cámara Web Logitech C920',
    code: 'VID-2023-017',
    condition: 'Malo',
    categoryId: 'technology',
    typeId: 'tech-webcam',
    groupKey: 'webcam-logitech-c920',
    groupName: 'Webcams Logitech C920',
    groupIcon: 'videocam',
    serial: 'SN: LOG-C920-017',
    locationId: 'computer-lab',
    location: 'Laboratorio de Cómputo',
  },
  {
    id: 'asset-7',
    name: 'Impresora HP LaserJet Pro M404',
    code: 'IMP-2022-011',
    condition: 'Mantenimiento',
    categoryId: 'technology',
    typeId: 'tech-printer',
    groupKey: 'impresora-hp-laserjet-m404',
    groupName: 'Impresoras HP LaserJet Pro M404',
    groupIcon: 'print',
    serial: 'SN: HP-M404-011',
    locationId: 'teachers-room',
    location: 'Sala de Profesores',
  },
  {
    id: 'asset-8',
    name: 'Tablet Samsung Galaxy Tab A8',
    code: 'TAB-2024-008',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-tablet',
    groupKey: 'tablet-samsung-galaxy-tab-a8',
    groupName: 'Tablets Samsung Galaxy Tab A8',
    groupIcon: 'tablet_mac',
    serial: 'SN: SAM-TABA8-008',
    locationId: 'classroom-101',
    location: 'Aula 101 - Pabellón A',
  },
  {
    id: 'asset-30',
    name: 'Tablet Samsung Galaxy Tab A8',
    code: 'TAB-2024-009',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-tablet',
    groupKey: 'tablet-samsung-galaxy-tab-a8',
    groupName: 'Tablets Samsung Galaxy Tab A8',
    groupIcon: 'tablet_mac',
    serial: 'SN: SAM-TABA8-009',
    locationId: 'classroom-101',
    location: 'Aula 101 - Pabellón A',
  },
  {
    id: 'asset-9',
    name: 'Monitor LG 24MK430H',
    code: 'MON-2023-031',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-monitor',
    groupKey: 'monitor-lg-24mk430h',
    groupName: 'Monitores LG 24MK430H',
    groupIcon: 'monitor',
    serial: 'SN: LG-24MK-031',
    locationId: 'computer-lab',
    location: 'Laboratorio de Cómputo',
  },
  {
    id: 'asset-31',
    name: 'Monitor LG 24MK430H',
    code: 'MON-2023-032',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-monitor',
    groupKey: 'monitor-lg-24mk430h',
    groupName: 'Monitores LG 24MK430H',
    groupIcon: 'monitor',
    serial: 'SN: LG-24MK-032',
    locationId: 'computer-lab',
    location: 'Laboratorio de Cómputo',
  },
  {
    id: 'asset-10',
    name: 'Micrófono Inalámbrico Shure BLX24',
    code: 'AUD-2022-019',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-microphone',
    groupKey: 'microfono-shure-blx24',
    groupName: 'Micrófonos Shure BLX24',
    groupIcon: 'mic_external_on',
    serial: 'SN: SHR-BLX24-019',
    locationId: 'auditorium',
    location: 'Auditorio Principal',
  },
  {
    id: 'asset-11',
    name: 'Cable HDMI 5 Metros',
    code: 'ACC-2023-108',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-hdmi-cable',
    groupKey: 'cable-hdmi-5-metros',
    groupName: 'Cables HDMI 5 Metros',
    groupIcon: 'settings_input_hdmi',
    serial: 'SN: HDMI-5M-108',
    locationId: 'auditorium',
    location: 'Auditorio Principal',
  },
  {
    id: 'asset-32',
    name: 'Cable HDMI 5 Metros',
    code: 'ACC-2023-109',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-hdmi-cable',
    groupKey: 'cable-hdmi-5-metros',
    groupName: 'Cables HDMI 5 Metros',
    groupIcon: 'settings_input_hdmi',
    serial: 'SN: HDMI-5M-109',
    locationId: 'auditorium',
    location: 'Auditorio Principal',
  },
  {
    id: 'asset-12',
    name: 'Puntero Láser Kensington',
    code: 'ACC-2023-076',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-laser-pointer',
    groupKey: 'puntero-laser-kensington',
    groupName: 'Punteros Láser Kensington',
    groupIcon: 'ads_click',
    serial: 'SN: KNS-LSR-076',
    locationId: 'auditorium',
    location: 'Auditorio Principal',
  },
  {
    id: 'asset-33',
    name: 'Puntero Láser Kensington',
    code: 'ACC-2023-077',
    condition: 'Bueno',
    categoryId: 'technology',
    typeId: 'tech-laser-pointer',
    groupKey: 'puntero-laser-kensington',
    groupName: 'Punteros Láser Kensington',
    groupIcon: 'ads_click',
    serial: 'SN: KNS-LSR-077',
    locationId: 'auditorium',
    location: 'Auditorio Principal',
  },
  {
    id: 'asset-13',
    name: 'Switch Cisco 24 Puertos',
    code: 'NET-2021-004',
    condition: 'Dado de baja',
    categoryId: 'technology',
    typeId: 'tech-router',
    groupKey: 'switch-cisco-24-puertos',
    groupName: 'Switches Cisco 24 Puertos',
    groupIcon: 'router',
    serial: 'SN: CSC-SW24-004',
    locationId: 'computer-lab',
    location: 'Laboratorio de Cómputo',
  },
  {
    id: 'asset-14',
    name: 'Escritorio Melamina Docente',
    code: 'MOB-2023-014',
    condition: 'Bueno',
    categoryId: 'furniture',
    typeId: 'furniture-desk',
    groupKey: 'escritorio-melamina-docente',
    groupName: 'Escritorios Melamina Docente',
    groupIcon: 'table_restaurant',
    serial: 'SN: MOB-DSK-014',
    locationId: 'classroom-101',
    location: 'Aula 101 - Pabellón A',
  },
  {
    id: 'asset-34',
    name: 'Escritorio Melamina Docente',
    code: 'MOB-2023-015',
    condition: 'Bueno',
    categoryId: 'furniture',
    typeId: 'furniture-desk',
    groupKey: 'escritorio-melamina-docente',
    groupName: 'Escritorios Melamina Docente',
    groupIcon: 'table_restaurant',
    serial: 'SN: MOB-DSK-015',
    locationId: 'classroom-101',
    location: 'Aula 101 - Pabellón A',
  },
  {
    id: 'asset-15',
    name: 'Silla Ergonómica Operativa',
    code: 'MOB-2024-022',
    condition: 'Regular',
    categoryId: 'furniture',
    typeId: 'furniture-chair',
    groupKey: 'silla-ergonomica-operativa',
    groupName: 'Sillas Ergonómicas Operativas',
    groupIcon: 'chair',
    serial: 'SN: MOB-CHR-022',
    locationId: 'teachers-room',
    location: 'Sala de Profesores',
  },
  {
    id: 'asset-35',
    name: 'Silla Ergonómica Operativa',
    code: 'MOB-2024-023',
    condition: 'Bueno',
    categoryId: 'furniture',
    typeId: 'furniture-chair',
    groupKey: 'silla-ergonomica-operativa',
    groupName: 'Sillas Ergonómicas Operativas',
    groupIcon: 'chair',
    serial: 'SN: MOB-CHR-023',
    locationId: 'teachers-room',
    location: 'Sala de Profesores',
  },
  {
    id: 'asset-16',
    name: 'Archivador Metálico 4 Gavetas',
    code: 'MOB-2021-005',
    condition: 'Bueno',
    categoryId: 'furniture',
    typeId: 'furniture-file-cabinet',
    groupKey: 'archivador-metalico-4-gavetas',
    groupName: 'Archivadores Metálicos 4 Gavetas',
    groupIcon: 'inventory_2',
    serial: 'SN: MOB-ARC-005',
    locationId: 'teachers-room',
    location: 'Sala de Profesores',
  },
  {
    id: 'asset-17',
    name: 'Estante Metálico Reforzado',
    code: 'MOB-2022-017',
    condition: 'Malo',
    categoryId: 'furniture',
    typeId: 'furniture-shelf',
    groupKey: 'estante-metalico-reforzado',
    groupName: 'Estantes Metálicos Reforzados',
    groupIcon: 'inventory_2',
    serial: 'SN: MOB-EST-017',
    locationId: 'sports-warehouse',
    location: 'Almacén Deportivo',
  },
  {
    id: 'asset-18',
    name: 'Microscopio Biológico Binocular',
    code: 'LAB-2024-003',
    condition: 'Bueno',
    categoryId: 'laboratory',
    typeId: 'lab-microscope',
    groupKey: 'microscopio-biologico-binocular',
    groupName: 'Microscopios Biológicos Binoculares',
    groupIcon: 'biotech',
    serial: 'SN: LAB-MIC-003',
    locationId: 'science-lab',
    location: 'Laboratorio de Ciencias',
  },
  {
    id: 'asset-36',
    name: 'Microscopio Biológico Binocular',
    code: 'LAB-2024-004',
    condition: 'Bueno',
    categoryId: 'laboratory',
    typeId: 'lab-microscope',
    groupKey: 'microscopio-biologico-binocular',
    groupName: 'Microscopios Biológicos Binoculares',
    groupIcon: 'biotech',
    serial: 'SN: LAB-MIC-004',
    locationId: 'science-lab',
    location: 'Laboratorio de Ciencias',
  },
  {
    id: 'asset-19',
    name: 'Balanza Digital Ohaus',
    code: 'LAB-2023-010',
    condition: 'Regular',
    categoryId: 'laboratory',
    typeId: 'lab-scale',
    groupKey: 'balanza-digital-ohaus',
    groupName: 'Balanzas Digitales Ohaus',
    groupIcon: 'scale',
    serial: 'SN: LAB-BAL-010',
    locationId: 'science-lab',
    location: 'Laboratorio de Ciencias',
  },
  {
    id: 'asset-37',
    name: 'Balanza Digital Ohaus',
    code: 'LAB-2023-011',
    condition: 'Bueno',
    categoryId: 'laboratory',
    typeId: 'lab-scale',
    groupKey: 'balanza-digital-ohaus',
    groupName: 'Balanzas Digitales Ohaus',
    groupIcon: 'scale',
    serial: 'SN: LAB-BAL-011',
    locationId: 'science-lab',
    location: 'Laboratorio de Ciencias',
  },
  {
    id: 'asset-20',
    name: 'Kit de Química Básica',
    code: 'LAB-2024-021',
    condition: 'Bueno',
    categoryId: 'laboratory',
    typeId: 'lab-chemistry-kit',
    groupKey: 'kit-quimica-basica',
    groupName: 'Kits de Química Básica',
    groupIcon: 'science',
    serial: 'SN: LAB-KQ-021',
    locationId: 'science-lab',
    location: 'Laboratorio de Ciencias',
  },
  {
    id: 'asset-21',
    name: 'Fuente de Poder Regulable',
    code: 'LAB-2022-009',
    condition: 'Mantenimiento',
    categoryId: 'laboratory',
    typeId: 'lab-power-supply',
    groupKey: 'fuente-poder-regulable',
    groupName: 'Fuentes de Poder Regulables',
    groupIcon: 'power',
    serial: 'SN: LAB-FTR-009',
    locationId: 'science-lab',
    location: 'Laboratorio de Ciencias',
  },
  {
    id: 'asset-22',
    name: 'Balón de Fútbol Molten #5',
    code: 'DEP-2024-002',
    condition: 'Bueno',
    categoryId: 'sports',
    typeId: 'sports-ball',
    groupKey: 'balon-futbol-molten',
    groupName: 'Balones de Fútbol Molten',
    groupIcon: 'sports_soccer',
    serial: 'SN: DEP-BAL-002',
    locationId: 'sports-warehouse',
    location: 'Almacén Deportivo',
  },
  {
    id: 'asset-38',
    name: 'Balón de Fútbol Molten #5',
    code: 'DEP-2024-003',
    condition: 'Bueno',
    categoryId: 'sports',
    typeId: 'sports-ball',
    groupKey: 'balon-futbol-molten',
    groupName: 'Balones de Fútbol Molten',
    groupIcon: 'sports_soccer',
    serial: 'SN: DEP-BAL-003',
    locationId: 'sports-warehouse',
    location: 'Almacén Deportivo',
  },
  {
    id: 'asset-23',
    name: 'Conos de Entrenamiento Set x20',
    code: 'DEP-2023-019',
    condition: 'Bueno',
    categoryId: 'sports',
    typeId: 'sports-cone',
    groupKey: 'conos-entrenamiento-set-20',
    groupName: 'Conos de Entrenamiento Set x20',
    groupIcon: 'sports',
    serial: 'SN: DEP-CNO-019',
    locationId: 'sports-warehouse',
    location: 'Almacén Deportivo',
  },
  {
    id: 'asset-39',
    name: 'Conos de Entrenamiento Set x20',
    code: 'DEP-2023-020',
    condition: 'Bueno',
    categoryId: 'sports',
    typeId: 'sports-cone',
    groupKey: 'conos-entrenamiento-set-20',
    groupName: 'Conos de Entrenamiento Set x20',
    groupIcon: 'sports',
    serial: 'SN: DEP-CNO-020',
    locationId: 'sports-warehouse',
    location: 'Almacén Deportivo',
  },
  {
    id: 'asset-24',
    name: 'Colchoneta de Gimnasia 1x2 m',
    code: 'DEP-2022-011',
    condition: 'Regular',
    categoryId: 'sports',
    typeId: 'sports-mat',
    groupKey: 'colchoneta-gimnasia-1x2',
    groupName: 'Colchonetas de Gimnasia 1x2 m',
    groupIcon: 'fitness_center',
    serial: 'SN: DEP-COL-011',
    locationId: 'sports-warehouse',
    location: 'Almacén Deportivo',
  },
  {
    id: 'asset-40',
    name: 'Colchoneta de Gimnasia 1x2 m',
    code: 'DEP-2022-012',
    condition: 'Bueno',
    categoryId: 'sports',
    typeId: 'sports-mat',
    groupKey: 'colchoneta-gimnasia-1x2',
    groupName: 'Colchonetas de Gimnasia 1x2 m',
    groupIcon: 'fitness_center',
    serial: 'SN: DEP-COL-012',
    locationId: 'sports-warehouse',
    location: 'Almacén Deportivo',
  },
  {
    id: 'asset-25',
    name: 'Red de Vóley Profesional',
    code: 'DEP-2021-004',
    condition: 'Malo',
    categoryId: 'sports',
    typeId: 'sports-net',
    groupKey: 'red-voley-profesional',
    groupName: 'Redes de Vóley Profesional',
    groupIcon: 'sports_volleyball',
    serial: 'SN: DEP-RDV-004',
    locationId: 'sports-warehouse',
    location: 'Almacén Deportivo',
  },
  {
    id: 'asset-26',
    name: 'Balón de Básquet Spalding',
    code: 'DEP-2024-014',
    condition: 'Dado de baja',
    categoryId: 'sports',
    typeId: 'sports-ball',
    groupKey: 'balon-basquet-spalding',
    groupName: 'Balones de Básquet Spalding',
    groupIcon: 'sports_basketball',
    serial: 'SN: DEP-BSQ-014',
    locationId: 'sports-warehouse',
    location: 'Almacén Deportivo',
  },
];

export const MOCK_CATEGORIES: Category[] = MOCK_CATEGORY_DEFINITIONS.map((categoryDefinition) => ({
  id: categoryDefinition.id,
  name: categoryDefinition.name,
  icon: categoryDefinition.icon,
  typesCount: categoryDefinition.types.length,
  assetsCount: MOCK_INVENTORY_ASSETS.filter((asset) => asset.categoryId === categoryDefinition.key).length,
  types: categoryDefinition.types.map((type) => ({
    ...type,
    attributes: type.attributes.map((attribute) => ({ ...attribute })),
  })),
}));

export const MOCK_CATEGORY_FILTERS = MOCK_CATEGORY_DEFINITIONS.map(({ key, name }) => ({
  id: key,
  name,
}));

export function isLoanSelectableAssetCondition(condition: MockAssetCondition): boolean {
  return condition === 'Bueno' || condition === 'Regular';
}
